version: '3.2'

services:
  db:
    image: mariadb:10.5.8
    restart: always
    environment:
      - MYSQL_DATABASE=java_test
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=12345678
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - 3306:3306
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=12345678
    ports:
      - 8091:80
